import os

env = Environment(ENV = os.environ)

env.Append(CPPPATH = [
    '#.',
    '#../src/parser/',
    '#../inc/'])

env.Append(LIBPATH = [
    './lib'
    ])

Export('env')
SConscript(['../src/parser/SConscript'])

env.Program(target='utest', LIBS=['libterminal'], source=['termutest.c',         
                                                          'ringbutest.c',
                                                          'myposixutest.c',
                                                          'termutest_mock.c',
                                                          'utest.c'])
