import os
env = Environment(ENV = os.environ)

env.Append(LIBPATH = [
    'lib'
    ])

Export('env')
SConscript(['SConscript'])

env.Program(target='termtest', LIBS=['libterminal'], source=['termutest.c',
                                                             'termutest_mock.c'] )
