env = Environment()

env.Append(LIBPATH = [
    'lib'
    ])

Export('env')
SConscript(['SConscript'])

env.Program(target='utest', LIBS=['libterminal'], source=['termutest.c',         
                                                          'ringbutest.c',
                                                          'myposixutest.c',
                                                          'termutest_mock.c',
                                                          'utest.c'])
